### ISSUE TITLE
Delay in going from Camera or Visit Report to Home screen

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/Android-Sitter-Mobile#12]
APK August 22. Android version 8.0
After taking/saving a photo or Sending a Visit Report. I am getting a black screen with about a 5-9 second delay before my Home screen refreshes. I tried doing it a few times and it varies on the delay time, but the black screen is not just a flash it will hold in that position for a few seconds.

**Comment by teddyhoo** [comment]
As per email with the distributed APK, the issue was related to thread to rebuild Main Activity UI that existed in previous design implementation. The Main Activity was being build by two different threads. I am running the non-fixed version on my device (Android 6.0) and I see this in the log output.

The 7th line of the log output shows that 35 frames were skipped in updating the UI and giving a weak warning signal that too much work is being done on the main thread. 

08-24 11:14:04.304 4427-4427/com.leashtime.sitterapp I/System.out: ON START CALLING IS NETWORK AVAIL
08-24 11:14:04.749 4427-4427/com.leashtime.sitterapp I/System.out: Internet is available
08-24 11:14:04.934 4427-4427/com.leashtime.sitterapp I/System.out: BROAD CAST RECEIVER CALLING IS NETWORK AVAIL
    Is network available called
08-24 11:14:05.314 4427-4427/com.leashtime.sitterapp I/System.out: Internet is available
08-24 11:14:05.339 4427-4427/com.leashtime.sitterapp I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
08-24 11:14:05.369 4427-4427/com.leashtime.sitterapp D/ViewRootImpl: #1 mView = android.widget.LinearLayout{327b217 V.E...... ......I. 0,0-0,0 #102039d android:id/toast_layout_root}
08-24 11:14:05.459 4427-7603/com.leashtime.sitterapp D/mali_winsys: new_window_surface returns 0x3000,  [350x78]-format:1
08-24 11:14:05.474 4427-4427/com.leashtime.sitterapp D/libEGL: eglTerminate EGLDisplay = 0xbeb448b4
    eglTerminate EGLDisplay = 0xbeb448b4
08-24 11:14:05.474 4427-4440/com.leashtime.sitterapp E/BufferQueueProducer: [SurfaceTexture-0-4427-1] dequeueBuffer: BufferQueue has been abandoned
08-24 11:14:05.484 4427-4427/com.leashtime.sitterapp D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
08-24 11:14:05.484 4427-4427/com.leashtime.sitterapp I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1200902 time:295798
08-24 11:14:05.509 4427-4441/com.leashtime.sitterapp E/BufferQueueProducer: [SurfaceTexture-0-4427-1] dequeueBuffer: BufferQueue has been abandoned
08-24 11:14:05.539 4427-4526/com.leashtime.sitterapp E/BufferQueueProducer: [SurfaceTexture-0-4427-1] dequeueBuffer: BufferQueue has been abandoned
08-24 11:14:05.574 4427-4440/com.leashtime.sitterapp E/BufferQueueProducer: [SurfaceTexture-0-4427-1] dequeueBuffer: BufferQueue has been abandoned
08-24 11:14:05.609 4427-11477/com.leashtime.sitterapp E/BufferQueueProducer: [SurfaceTexture-0-4427-1] dequeueBuffer: BufferQueue has been abandoned
08-24 11:14:05.639 4427-11477/com.leashtime.sitterapp E/BufferQueueProducer: [SurfaceTexture-0-4427-1] dequeueBuffer: BufferQueue has been abandoned
08-24 11:14:05.654 4427-4427/com.leashtime.sitterapp D/SensorManager: unregisterListener ::   
08-24 11:14:05.659 4427-4427/com.leashtime.sitterapp D/ViewRootImpl: #3 mView = null
08-24 11:14:05.679 4427-4441/com.leashtime.sitterapp E/BufferQueueProducer: [SurfaceTexture-0-4427-1] dequeueBuffer: BufferQueue has been abandoned
08-24 11:14:05.704 4427-11477/com.leashtime.sitterapp E/BufferQueueProducer: [SurfaceTexture-0-4427-1] dequeueBuffer: BufferQueue has been abandoned
08-24 11:14:05.739 4427-4526/com.leashtime.sitterapp E/BufferQueueProducer: [SurfaceTexture-0-4427-1] dequeueBuffer: BufferQueue has been abandoned
08-24 11:14:08.839 4427-4427/com.leashtime.sitterapp D/ViewRootImpl: #3 mView = null

**Comment by teddyhoo** [comment]
I found similar issue with the initial boot up login page. I created a thread to do all the login and setup o the list view and then, inexplicably, ran the thread on the Main UI thread (all UI updates are exclusively handled through system Main UI thread). It acts a natural bottleneck, therefore, you should do processing of setup activity off that thread and only invoke thread when you have narrowed down commands to purely UI ones. 

Additionally, the cell updates were not properly handling swithcing icon from note icon to envelope icon when sending visit report. This has been corrected.

**Comment by mattleashtime** [comment]
(Testing LEASHTIME_2_0_AUGUST_24_2018.apk)

Larger "X" is nice, but it is still taking 1 second to respond.  

Return to foreground takes about 3-5 seconds total.  About a second for the blue screen to appear, and then 2-4 seconds before visits are rendered.

**Comment by jodsmithLT** [comment]
(Testing LEASHTIME_2_0_AUGUST_24_2018.apk)
Still having the delay in transitions from Camera and Visit Report

**Comment by mattleashtime** [comment]
Testing LEASHTIME_2_0_AUGUST_27_2018.apk

Delay returning from Visit Report  is down to 1/2 - 3/4 second.  Much better.
Delay returning from taking photo is down to 1/2 - 3/4 second.  Much better.
Delay returning to foreground is still about 5 seconds total.

**Comment by jodsmithLT** [comment]
Much better times for me too!

**Comment by teddyhoo** [comment]
I have implemented threading around sections of code that could block the main ui thread. Any onClick events tied to buttons (e.g. take picture) often trigger long running operations (write image to file). These are now threaded. This reduced burden of the master thread which is the only thread allowed to update UI. In other words, it is imperative to reduce burden placed upon UI. 

Additionally, tweaked the cell refresh update cycle by avoiding sending a notifyDataChanged call. Instead intercept cell event (swipe then tap), then directly update the cell.

**Comment by teddyhoo** [comment]
The report from everyone is that this is seemingly much faster. Keep testing. I will close this ticket out because it is a broad based change and if there are any side effects or gaps, they will be better addressed in specific incident tickets.
